# ngWelcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# destination: docs

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: BNDY-NET
title: BNDY-NET · Bendy's Personal Website
author: Bendy Zhang
email: zb@bndy.net

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bndy.net" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

languages: ["en", "cn"]
default_lang: "en"
exclude_from_localization: ["js", "img", "fonts", "font-awesome", "css", "html", "demo", "GitHubVisualizer"]
parallel_localization: false
